name: Pipeline PROD

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  test:
    uses: ./.github/workflows/test-prod.yml

  deploy-prod:
    name: Deploy to PROD
    needs: [test]
    uses: ./.github/workflows/deploy-prod.yml
    secrets:
      ENV_FILE_PROD: ${{ secrets.ENV_FILE_PROD }}
      FIREBASE_PROJECT_ID_PROD: ${{ secrets.FIREBASE_PROJECT_ID_PROD }}
      FIREBASE_SERVICE_ACCOUNT_PROD: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_PROD }}
