name: CI PROD

on:
  pull_request:
    branches: [master]
  workflow_dispatch:
  workflow_call:

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Cache
        uses: actions/cache@v2
        with:
          path: |
            ~/cache
            !~/cache/exclude
            **/node_modules
            ~/.cache
          key: ${{ runner.os }}-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-${{ hashFiles('package-lock.json') }}

      - name: Use Node.js ${{matrix.node-version}}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: npm install
        run: |
          npm ci
          npm --prefix functions ci functions
        env:
          CI: true

      - name: npm lint
        run: |
          npm run lint
          npm run lint:style

      - name: npm test:unit
        run: |
          npm run test:unit
        env:
          CI: true
